name: merged_and_status_done
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - uses: actions/checkout@v2
    - uses: ryubb/github-actions-test@v0.2.7
      with:
        notion-key: ${{ secrets.NOTION_KEY }}
        status-property: "Status"
        status-value: "Completed"
